name: 'Dropbox Download Action'
description: 'A Github Action to download directories from Dropbox'
inputs:
  dropbox-refresh-token:
    description: 'Dropbox Refresh Token'
    required: true
    default: ''
  source-path:
    description: 'The path of the folder which will be downloaded from Dropbox'
    required: true
  destination-path:
    description: 'The path which the downloaded folder will be placed'
    required: true
    default: 'dropbox-artifacts'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'gbrls/action-dropbox-download'
        path: '.dropbox'
    - name: 'run elixir'
      uses: docker://elixir
      env:
        DROPBOX_SL_TOKEN: ${{ inputs.dropbox-sl-token }}
        DROPBOX_REFRESH_TOKEN: ${{ inputs.dropbox-refresh-token }}
        DIR_PATH: ${{ inputs.source-path }}
        OUT_PATH: ${{ inputs.destination-path }}
      with:
        entrypoint: sh
        args: .dropbox/scripts/fetch-api.sh
