name: 'Dropbox Download Action'
description: 'A Github Action to download directories from Dropbox'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  dropbox-token:
    description: 'Dropbox API Token'
    required: true
runs:
  using: "composite"
  env:
    DROPBOX_TOKEN: ${{ inputs.dropbox-token }}}
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'gbrls/action-dropbox-download'
    - name: 'run elixir'
      uses: docker://elixir
      with:
        entrypoint: elixir
        args: scripts/main.exs
