name: 'Dropbox Download Action'
description: 'A Github Action to download directories from Dropbox'
inputs:
  dropbox-token:
    description: 'Dropbox API Token'
    required: true
  source-path:
    description: 'The path of the folder which will be downloaded from Dropbox'
    required: true
  destination-path:
    description: 'The path which the downloaded folder will be placed'
    required: true
    default: 'artifacts'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'gbrls/action-dropbox-download'
    - name: 'run elixir'
      uses: docker://elixir
      env:
        DROPBOX_TOKEN: ${{ inputs.dropbox-token }}
        DIR_PATH: ${{ inputs.source-path }}
      with:
        entrypoint: sh
        args: scripts/fetch-api.sh
