name: 'Dropbox Download Action'
description: 'A Github Action to download directories from Dropbox'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  dropbox-token:
    description: 'Dropbox API Token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'gbrls/action-dropbox-download'
    - name: 'run elixir'
      uses: docker://elixir
      env:
        DROPBOX_TOKEN: ${{ inputs.dropbox-token }}
      with:
        entrypoint: sh
        args: scripts/fetch-api.sh
    - uses: actions/upload-artifact@v3
      with:
        name: data.zip
        path: data.zip
